export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM';

// TODO: LOADERS
export const SHOW_LOADER = 'SHOW_LOADER';
export const CLOSE_LOADER = 'CLOSE_LOADER';

export const RECIEVE_PROJECTS = 'RECIEVE_PROJECTS';
